# Generated by Django 6.0.3 on 2026-07-17 00:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=160)),
                ('summary', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversación del asistente',
                'verbose_name_plural': 'conversaciones del asistente',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('identity', 'Identidad'), ('preferences', 'Preferencias'), ('people', 'Personas importantes'), ('dates', 'Fechas especiales'), ('budget', 'Presupuesto'), ('products', 'Productos'), ('personalization', 'Personalizaciones'), ('sizes', 'Tallas o medidas'), ('delivery', 'Entrega'), ('payment', 'Forma de pago'), ('other', 'Otros')], max_length=32)),
                ('key', models.SlugField(max_length=90)),
                ('content', models.CharField(max_length=600)),
                ('search_text', models.CharField(blank=True, max_length=900)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('importance', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('memory_type', models.CharField(choices=[('observation', 'Dato confirmado'), ('preference', 'Preferencia'), ('permanent', 'Instrucción permanente'), ('temporary', 'Información temporal')], default='observation', max_length=20)),
                ('mention_count', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(choices=[('chat', 'Conversación'), ('profile', 'Perfil'), ('purchase', 'Compra'), ('manual', 'Edición manual')], default='chat', max_length=20)),
                ('consent_status', models.CharField(choices=[('pending', 'Pendiente'), ('granted', 'Autorizado'), ('denied', 'Rechazado')], default='granted', max_length=16)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recuerdo del asistente',
                'verbose_name_plural': 'recuerdos del asistente',
                'ordering': ['-importance', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=16)),
                ('content', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='asistente.assistantconversation')),
            ],
            options={
                'verbose_name': 'mensaje del asistente',
                'verbose_name_plural': 'mensajes del asistente',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_enabled', models.BooleanField(default=False)),
                ('memory_paused_until', models.DateTimeField(blank=True, null=True)),
                ('allowed_categories', models.JSONField(blank=True, default=list)),
                ('conversation_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de memoria',
                'verbose_name_plural': 'perfiles de memoria',
            },
        ),
        migrations.AddIndex(
            model_name='assistantconversation',
            index=models.Index(fields=['user', 'is_active', 'updated_at'], name='asistente_a_user_id_daf890_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmemory',
            index=models.Index(fields=['user', 'category', 'consent_status'], name='asistente_a_user_id_d600fe_idx'),
        ),
        migrations.AddIndex(
            model_name='assistantmemory',
            index=models.Index(fields=['user', 'updated_at'], name='asistente_a_user_id_1fa5ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistantmemory',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_memory_key_per_user'),
        ),
        migrations.AddIndex(
            model_name='assistantmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='asistente_a_convers_675b61_idx'),
        ),
    ]
