# Generated by Django 6.0.3 on 2026-07-17 00:36

import carrito.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0046_renombrar_referencias_sin_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrito_persistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lista persistente',
                'verbose_name_plural': 'listas persistentes',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('texto_personalizado', models.CharField(blank=True, max_length=180)),
                ('color', models.CharField(blank=True, max_length=80)),
                ('variante', models.CharField(blank=True, max_length=80)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('mensaje_regalo', models.TextField(blank=True, max_length=500)),
                ('imagen_cliente', models.ImageField(blank=True, null=True, upload_to='personalizaciones/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), carrito.models.validate_customer_image_size])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_items', to='productos.producto')),
            ],
            options={
                'verbose_name': 'producto de la lista',
                'verbose_name_plural': 'productos de la lista',
                'ordering': ['creado', 'id'],
                'indexes': [models.Index(fields=['carrito', 'producto'], name='carrito_car_carrito_422b5d_idx')],
                'constraints': [models.UniqueConstraint(fields=('carrito', 'producto'), name='unique_product_per_persistent_cart')],
            },
        ),
    ]
