# Generated by Django 6.0.3 on 2026-07-17 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('session_key__isnull', True), ('usuario__isnull', False)), models.Q(('session_key__isnull', False), ('usuario__isnull', True)), _connector='OR'), name='cart_has_exactly_one_owner'),
        ),
    ]
