# Generated by Codex on 2026-03-30

from django.db import migrations


def seed_catalogo(apps, schema_editor):
    Categoria = apps.get_model('productos', 'Categoria')
    Producto = apps.get_model('productos', 'Producto')

    categorias = {}
    for nombre in [
        'Cumpleaños y desayunos',
        'Amor y aniversario',
        'Tematicos e infantiles',
        'Mini detalles',
        'Frutales y flores',
        'Regalos premium',
    ]:
        categorias[nombre], _ = Categoria.objects.get_or_create(nombre=nombre)

    Producto.objects.filter(nombre__in=['f', 'h']).delete()

    productos = [
        ('Cumple azul premium', 'Referencia cumpleañera con caja en madera, globos, fruta, waffles y decoracion. Precio base sujeto a personalizacion.', '81000.00', 6, 'Cumpleaños y desayunos', 'referencias/referencia-03.png', True),
        ('Desayuno globos pastel', 'Bandeja sorpresa con globos, yogurt, sandwich, jugo y detalles visuales suaves.', '80000.00', 5, 'Cumpleaños y desayunos', 'referencias/referencia-04.png', True),
        ('Caja aniversario te amo', 'Caja romantica con globo burbuja, waffles, jugo y mensaje especial.', '75000.00', 4, 'Amor y aniversario', 'referencias/referencia-05.png', True),
        ('Amor delicado rosa', 'Referencia romantica en tonos rosa con globo, dulces y presentacion suave.', '89000.00', 4, 'Amor y aniversario', 'referencias/referencia-06.png', False),
        ('Rose gold cumpleañero', 'Caja cumpleañera con globos rose gold, frutas, waffles y postre.', '77000.00', 5, 'Cumpleaños y desayunos', 'referencias/referencia-07.png', True),
        ('Cumple lila fantasia', 'Opcion juvenil y colorida con snacks, desayuno y decoracion personalizada.', '75000.00', 4, 'Cumpleaños y desayunos', 'referencias/referencia-08.png', False),
        ('Black and gold deluxe', 'Detalle premium con globos negro y dorado, fruta y una presentacion mas sofisticada.', '94000.00', 3, 'Regalos premium', 'referencias/referencia-09.png', True),
        ('Trio corazones sorpresa', 'Coleccion romantica con corazones, chocolates, rosas y cajas para sorprender.', '63000.00', 5, 'Amor y aniversario', 'referencias/referencia-10.png', False),
        ('Tematicos con personaje', 'Referencias con Hello Kitty, Mario, fotos y personajes elegidos por el cliente.', '44000.00', 6, 'Tematicos e infantiles', 'referencias/referencia-11.png', True),
        ('Mini detalles con globo', 'Mini regalos con globos, snacks y mensajes para fechas puntuales.', '27000.00', 8, 'Mini detalles', 'referencias/referencia-12.png', False),
        ('Rosas y fresas premium', 'Propuestas con rosas, fresas cubiertas, licor y presentaciones de alto impacto.', '173000.00', 2, 'Frutales y flores', 'referencias/referencia-13.png', True),
        ('Bunny y corazon frutal', 'Detalle creativo con tematica tierna y tabla frutal en forma de corazon.', '42000.00', 4, 'Frutales y flores', 'referencias/referencia-14.png', False),
        ('Buenos dias con amor', 'Desayuno pequeno con bebidas, snacks y mensaje para sorprender desde temprano.', '55000.00', 5, 'Amor y aniversario', 'referencias/referencia-15.png', False),
        ('Dia especial express', 'Mini detalle con empaque protagonista para regalos rapidos y fechas cortas.', '28000.00', 7, 'Mini detalles', 'referencias/referencia-16.png', False),
        ('Desayuno mariposa rosa', 'Mesa o bandeja en madera con globos, yogurt, jugo y decoracion femenina.', '89000.00', 4, 'Cumpleaños y desayunos', 'referencias/referencia-17.png', False),
        ('Combo snack con globos', 'Combinacion de snacks y globos metalizados para una sorpresa vistosa.', '88000.00', 5, 'Cumpleaños y desayunos', 'referencias/referencia-18.png', False),
        ('Caja corazon premium', 'Caja fina en forma de corazon con sandwich, jugo, rosas, chocolates o peluche.', '122000.00', 3, 'Regalos premium', 'referencias/referencia-19.png', True),
    ]

    for nombre, descripcion, precio, stock, categoria, imagen, destacado in productos:
        Producto.objects.update_or_create(
            nombre=nombre,
            defaults={
                'descripcion': descripcion,
                'precio': precio,
                'stock': stock,
                'categoria': categorias[categoria],
                'imagen': imagen,
                'destacado': destacado,
            },
        )


def unseed_catalogo(apps, schema_editor):
    Producto = apps.get_model('productos', 'Producto')
    Categoria = apps.get_model('productos', 'Categoria')

    nombres = [
        'Cumple azul premium',
        'Desayuno globos pastel',
        'Caja aniversario te amo',
        'Amor delicado rosa',
        'Rose gold cumpleanero',
        'Cumple lila fantasia',
        'Black and gold deluxe',
        'Trio corazones sorpresa',
        'Tematicos con personaje',
        'Mini detalles con globo',
        'Rosas y fresas premium',
        'Bunny y corazon frutal',
        'Buenos dias con amor',
        'Dia especial express',
        'Desayuno mariposa rosa',
        'Combo snack con globos',
        'Caja corazon premium',
    ]

    Producto.objects.filter(nombre__in=nombres).delete()
    Categoria.objects.filter(
        nombre__in=[
            'Cumpleaños y desayunos',
            'Amor y aniversario',
            'Tematicos e infantiles',
            'Mini detalles',
            'Frutales y flores',
            'Regalos premium',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_catalogo, unseed_catalogo),
    ]
