# Generated by Django 6.0.3 on 2026-05-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_seed_videos_elaboracion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoelaboracion',
            options={'ordering': ['orden', '-destacado', '-fecha_creacion'], 'verbose_name': 'video de elaboración', 'verbose_name_plural': 'videos de elaboración'},
        ),
        migrations.AlterField(
            model_name='interaccioncliente',
            name='tipo',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('carrito', 'Carrito'), ('catalogo', 'Catálogo'), ('otro', 'Otro')], default='otro', max_length=40),
        ),
    ]
