# Generated by Django 6.0.3 on 2026-05-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0031_corregir_tildes_textos_catalogo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InteraccionCliente',
        ),
    ]
